import numpy as np
import torch
from torch import nn

import cv2 # needed for inpainting
import copy # needed for randomizing model weights

from typing import Callable, Collection, Literal, Union


SpacingType = Union[Literal["LINEAR"], Literal[""]] # TODO add other spacing types
PerturbationType = Union[Literal["BLACK"], Literal["INTERPOLATE"]]


#
# Basic functions
#

def inpaint(image: torch.Tensor, mask: torch.Tensor, radius: float) -> torch.Tensor:
    """
    Obscure part of an image by inpainting.

    ### Input

    image: Tensor containing an image of shape `(3, H, W)` or `(B, 3, H, W)`.
    mask: Tensor of the same shape as `image` and (preferably) of boolean type.
    radius: Inpaint radius passed to `cv2.inpaint`.

    ### Output

    Tensor of the same shape as `image` containing the inpainted image.
    """
    # -- handle batch

    if len(image.shape) == 4:
        inpaints = [inpaint(i, m, radius) for i, m in zip(image, mask)]

        return torch.stack(inpaints, dim=0)

    # -- handle single image

    # convert to numpy
    image_np = (image * 255).to(torch.uint8).permute(1, 2, 0).cpu().numpy()
    mask_np = mask.to(torch.uint8).cpu().numpy()

    # apply inpaint function
    image_inpainted_np = cv2.inpaint(image_np, mask_np, inpaintRadius=radius, flags=cv2.INPAINT_TELEA)

    # convert to pytorch
    image_inpainted = torch.from_numpy(image_inpainted_np).permute(2, 0, 1).to(image.device) / 255

    return image_inpainted


def get_gradient(model: nn.Module, c: int, x: torch.Tensor) -> torch.Tensor:
    """
    Get the gradient of an ImageNet-classificator with respect to a point and a specific class.

    ### Input

    model: Pytorch module trained on ImageNet with output shape `(B, 1000)`.
    c: Class index; number between 0 and 999.
    x: Tensor containing an image of shape `(B, 3, H, W)`.

    ### Output

    Tensor of the same shape as `x` containing the gradient of `model` at point `x` with respect to class `c`.
    """
    x = x.detach().clone().requires_grad_(True)
    y = model(x)[..., c]
    y.backward(torch.ones_like(y))

    return x.grad # type: ignore (the gradient is always defined)


def randomize_model(model: nn.Module) -> nn.Module:
    """
    Get a deep copy of a model with randomized weights. Due to the different initialization standards
    of different modules, the scope of this function is limited to MLPs, CNNs and transformers.

    ### Input

    model: Pytorch module.

    ### Output

    Pytorch module of the same architecture as `model` with randomly initialized weights.
    """
    new_model = copy.deepcopy(model)

    # the following loop was generated by Microsoft Copilot
    for module in new_model.modules():
        if isinstance(module, (nn.Conv2d, nn.Linear)):
            # Kaiming Normal for layers with ReLU (safe default for CNNs and MLPs)
            torch.nn.init.kaiming_normal_(module.weight, mode='fan_out', nonlinearity='relu')
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            # Normal initialization for embeddings
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
        elif isinstance(module, nn.LayerNorm):
            # LayerNorm: weight = 1, bias = 0
            torch.nn.init.ones_(module.weight)
            torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.BatchNorm2d):
            # BatchNorm: weight = 1, bias = 0
            torch.nn.init.ones_(module.weight)
            torch.nn.init.zeros_(module.bias)

    return new_model


def normalize_explanation(explanation: torch.Tensor) -> torch.Tensor:
    """
    Normalization from Hedström et al.: "A Fresh Look at Sanity Checks for Saliency Maps".
    Useful for comparing explanations.

    IMPORTANT: The first dimension of `explanation` is for the batch, NOT the color channels.

    ### Input

    explanation: Tensor containing an explanation of shape `(B, H, W)`.

    ### Output

    Tensor of the same shape as `explanation` containing the normalized explanation.
    """
    return explanation / explanation.pow(2).flatten(1).mean(1).sqrt()


def visualize_explanation(explanation: torch.Tensor, quantile: float = 0.99) -> torch.Tensor:
    """
    Arbitrary method for making legible images out of explanations.

    ### Input

    explanation: Tensor containing an explanation of shape `(B, 3, H, W)`.
    quantile: Which quantile should be mapped to the maximum value.
    """
    # take average over color channels
    ex = explanation.mean(1)

    # divide by the given quantile
    q = ex.abs().flatten(1).quantile(quantile, dim=1)
    ex = ex / q.view(-1, 1, 1)

    # clip values between -1 and 1
    ex = ex.clip(-1, 1)

    # make positive values red and negative values blue as in Samek et al.: "Explaining Deep Neural Networks and Beyond: A Review of Methods and Applications"
    relu_pos = ex.relu()
    relu_neg = (-ex).relu()
    ex = torch.stack([
        1 - relu_neg, # more negative -> less red
        1 - relu_pos - relu_neg, # further from zero -> less green
        1 - relu_pos # more positive -> less blue
    ], dim=1)

    return ex


#
# Advanced functions
#

def get_perturbation_curve(
    model: nn.Module,
    c: int,
    target: torch.Tensor,
    explanation: torch.Tensor,
    n_points: int,
    perturbation: PerturbationType = "INTERPOLATE",
    spacing: SpacingType = "LINEAR",
    apply_softmax: bool = False,
) -> list[float]:
    """
    Get a perturbation curve as in IV.A. from Samek et al.: "Explaining Deep Neural Networks and Beyond: A Review of Methods and Applications".
    The target is perturbed to different amounts and the resulting model output is measured.

    ### Input

    model: Pytorch module trained on ImageNet with output shape `(B, 1000)`.
    c: Class index; number between 0 and 999.
    target: Tensor containing the target image of shape `(B, 3, H, W)`.
    explanation: Tensor containing an explanation to be evaluated by this function.
    n_points: Number of evaluation points from which make up the curve.
    perturbation: Perturbation type for generating the perturbed samples.
    spacing: Spacing type for the evaluation points.
    apply_softmax: Whether to apply softmax to the `model` output.

    ### Output

    List containing the model outputs at the evaluation points as `float`s.
    """
    ...


def verbose_iterate_explanation(
    explanation_method: Callable[[torch.Tensor, torch.Tensor], torch.Tensor],
    perturbation_method: Callable[[torch.Tensor, torch.Tensor], torch.Tensor],
    target: torch.Tensor,
    baseline: torch.Tensor,
    n_iterations: int,
    noise: float | Collection[float],
) -> tuple[list[torch.Tensor], list[torch.Tensor]]:
    """
    See `iterate_explanation` for an explanation of the function and its inputs.

    ### Output

    One list containing the baselines used and another list containing the resulting explanations.
    """
    baselines = []
    explanations = []

    # convert noise from float to list of floats
    if not isinstance(noise, Collection):
        noise = [noise] * n_iterations

    if len(noise) != n_iterations:
        raise ValueError("Number of noise values does not match number of iterations.")

    for _noise in noise:
        # get new explanation
        explanation = explanation_method(target, baseline + _noise * torch.randn_like(baseline))

        # store current baseline and explanation
        baselines.append(baseline)
        explanations.append(explanation)

        # get new baseline
        baseline = perturbation_method(target, explanation)

    return baselines, explanations


def iterate_explanation(
    explanation_method: Callable[[torch.Tensor, torch.Tensor], torch.Tensor],
    perturbation_method: Callable[[torch.Tensor, torch.Tensor], torch.Tensor],
    target: torch.Tensor,
    baseline: torch.Tensor,
    n_iterations: int,
    noise: float | Collection[float],
) -> torch.Tensor:
    """
    Iteratively apply an explanation method. Our main contribution from the paper.

    # Input

    explanation_method: Maps a `(target, baseline)`-pair to an explanation (e.g. Integrated Gradients).
    perturbation_method: Maps a `(target, explanation)`-pair to a new baseline.
    target: Tensor containing the target image of shape `(B, 3, H, W)`.
    baseline: Tensor containing the initial baseline of the same shape as `target`.
    n_iterations: Number of iterations.
    noise: How much Gaussian noise is applied to the baseline in each iteration. Can be a single value or a sequence of values, one for each iteration.

    ### Output

    Tensor of the same shape as `target` containing the final explanation.
    """
    baselines, explanations = verbose_iterate_explanation(explanation_method, perturbation_method, target, baseline, n_iterations, noise)

    return explanations[-1]
