import numpy as np
import torch
from torch import nn

import cv2 # needed for inpainting
import copy # needed for randomizing model weights

from typing import Callable, Collection, Literal, Union


SpacingType = Union[Literal["LINEAR"], Literal[""]] # TODO add other spacing types
PerturbationType = Union[Literal["BLACK"], Literal["INTERPOLATE"]]


#
# Basic functions
#

def inpaint(image: torch.Tensor, mask: torch.Tensor, radius: float) -> torch.Tensor:
    """
    Obscure part of an image by inpainting.

    ### Input

    image: Tensor containing an image of shape `(3, H, W)` or `(B, 3, H, W)`.
    mask: Tensor of shape `(H, W)` or `(B, H, W)` and (preferably) of boolean type.
    radius: Inpaint radius passed to `cv2.inpaint`.

    ### Output

    Tensor of the same shape as `image` containing the inpainted image.
    """
    # -- handle batch

    if len(image.shape) == 4:
        inpaints = [inpaint(i, m, radius) for i, m in zip(image, mask)]

        return torch.stack(inpaints, dim=0)

    # -- handle single image

    # convert to numpy
    image_np = (image * 255).to(torch.uint8).permute(1, 2, 0).cpu().numpy()
    mask_np = mask.to(torch.uint8).cpu().numpy()

    # apply inpaint function
    image_inpainted_np = cv2.inpaint(image_np, mask_np, inpaintRadius=radius, flags=cv2.INPAINT_TELEA)

    # convert to pytorch
    image_inpainted = torch.from_numpy(image_inpainted_np).permute(2, 0, 1).to(image.device) / 255

    return image_inpainted


def get_gradient(model: nn.Module, c: int | torch.Tensor, x: torch.Tensor) -> torch.Tensor:
    """
    Get the gradient of an ImageNet-classificator with respect to a point and a specific class.

    ### Input

    model: Pytorch module trained on ImageNet with output shape `(B, 1000)`.
    c: Class index; number between 0 and 999.
    x: Tensor containing an image of shape `(B, 3, H, W)`.

    ### Output

    Tensor of the same shape as `x` containing the gradient of `model` at point `x` with respect to class `c`.
    """
    x = x.detach().clone().requires_grad_(True)
    y = model(x)[torch.arange(len(x), device=x.device), c]
    y.backward(torch.ones_like(y))

    return x.grad # type: ignore (the gradient is always defined)


def randomize_model(model: nn.Module) -> nn.Module:
    """
    Get a deep copy of a model with randomized weights. Due to the different initialization standards
    of different modules, the scope of this function is limited to MLPs, CNNs and transformers.

    ### Input

    model: Pytorch module.

    ### Output

    Pytorch module of the same architecture as `model` with randomly initialized weights.
    """
    new_model = copy.deepcopy(model)

    # the following loop was generated by Microsoft Copilot
    for module in new_model.modules():
        if isinstance(module, (nn.Conv2d, nn.Linear)):
            # Kaiming Normal for layers with ReLU (safe default for CNNs and MLPs)
            torch.nn.init.kaiming_normal_(module.weight, mode='fan_out', nonlinearity='relu')
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            # Normal initialization for embeddings
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
        elif isinstance(module, nn.LayerNorm):
            # LayerNorm: weight = 1, bias = 0
            torch.nn.init.ones_(module.weight)
            torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.BatchNorm2d):
            # BatchNorm: weight = 1, bias = 0
            torch.nn.init.ones_(module.weight)
            torch.nn.init.zeros_(module.bias)

    return new_model


def normalize_explanation(explanation: torch.Tensor) -> torch.Tensor:
    """
    Normalization from Hedström et al.: "A Fresh Look at Sanity Checks for Saliency Maps".
    Useful for comparing explanations.

    IMPORTANT: The first dimension of `explanation` is for the batch, NOT the color channels.

    ### Input

    explanation: Tensor containing an explanation of shape `(B, H, W)`.

    ### Output

    Tensor of the same shape as `explanation` containing the normalized explanation.
    """
    return explanation / explanation.pow(2).flatten(1).mean(1).sqrt()


def visualize_explanation(explanation: torch.Tensor, quantile: float = 0.99) -> torch.Tensor:
    """
    Arbitrary method for making legible images out of explanations.

    ### Input

    explanation: Tensor containing an explanation of shape `(3, H, W)` or `(B, 3, H, W)`.
    quantile: Which quantile should be mapped to the maximum value.
    """
    # if explanation has no batch dimension, add it
    if len(explanation.shape) == 3:
        explanation = explanation.unsqueeze(0)

    # take average over color channels
    ex = explanation.mean(1)

    # divide by the given quantile
    q = ex.abs().flatten(1).quantile(quantile, dim=1)
    ex = ex / q.view(-1, 1, 1)

    # clip values between -1 and 1
    ex = ex.clip(-1, 1)

    # make positive values red and negative values blue as in Samek et al.: "Explaining Deep Neural Networks and Beyond: A Review of Methods and Applications"
    relu_pos = ex.relu()
    relu_neg = (-ex).relu()
    ex = torch.stack([
        1 - relu_neg, # more negative -> less red
        1 - relu_pos - relu_neg, # further from zero -> less green
        1 - relu_pos # more positive -> less blue
    ], dim=1)

    # move color channel dimension to the end (because plotly requires it)
    ex  = ex.permute(0, 2, 3, 1)

    # if batch size is one, remove batch dimension
    ex = ex.squeeze(0)

    # move to cpu (because plotly requires it)
    ex = ex.cpu()

    return ex


#
# Advanced functions
#

def get_perturbation_curve(
    model: nn.Module,
    c: int,
    target: torch.Tensor,
    explanation: torch.Tensor,
    n_points: int,
    perturbation: PerturbationType = "INTERPOLATE",
    spacing: SpacingType = "LINEAR", # TODO
    apply_softmax: bool = False,
) -> torch.Tensor:
    """
    Get a perturbation curve as in IV.A. from Samek et al.: "Explaining Deep Neural Networks and Beyond: A Review of Methods and Applications".
    The target is perturbed to different amounts and the resulting model output is measured.

    ### Input

    model: Pytorch module trained on ImageNet with output shape `(B, 1000)`.
    c: Class index; number between 0 and 999.
    target: Tensor containing the target image of shape `(B, 3, H, W)`.
    explanation: Tensor containing an explanation to be evaluated by this function of shape `(B, H, W)`.
    n_points: Number of evaluation points from which make up the curve.
    perturbation: Perturbation type for generating the perturbed samples.
    spacing: Spacing type for the evaluation points.
    apply_softmax: Whether to apply softmax to the `model` output.

    ### Output

    List containing the model outputs at the evaluation points as `float`s.
    """
    _values = []

    idx_batch = torch.arange(len(target), device=target.device)

    match perturbation:
        case "INTERPOLATE":
            perturbation_method = lambda target, mask: inpaint(target, mask, 5)
        case "BLACK":
            perturbation_method = lambda target, mask: torch.where(mask.unsqueeze(1).repeat(1, 3, 1, 1), 0, target)

    for t in np.linspace(0, 1, n_points):
        mask = explanation > explanation.flatten(1).quantile(1 - t, dim=1).view(-1, 1, 1)

        target_perturbed = perturbation_method(target, mask)

        with torch.no_grad():
            y = model(target_perturbed)

        if apply_softmax:
            y = y.softmax(1)

        _values.append(y[idx_batch, c].clone())

    values = torch.stack(_values, dim=1)

    return values
