[general]

image_path = "D:/ImageNet/ILSVRC/Data/CLS-LOC/test/"
n_samples = 5
classificator = "resnet50"
apply_softmax = false
device = "cuda"


[perturbation_curve]

n_steps = 11
type = "interpolate"


# -- Integrated Gradients
[method.IG]

description = "Integrated Gradients - Baseline method"

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 50, trapezoid = false}

baseline_method = "black"


# -- Iterative Integrated Gradients
[method.IIG]

description = "Iterative Integrated Gradients"

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 10, trapezoid = false}

baseline_method = "noisy_target"
baseline_parameters = {noise = 0.1}


[method.IIG.iterate]

n_iterations = 5
noise = 0.1
explanation_transforms = ["abs", "mean"]

perturbation_method = "inpaint_by_quantile"
perturbation_parameters = {quantile = 0.4, radius = 5}
