[general]

image_path = "D:/ImageNet/ILSVRC/Data/CLS-LOC/test/"
out_path = "output/test_vgg11"
n_samples = 4
# start_index = 10
batch_size = 2
classifier = "vgg11"
apply_softmax = false
device = "cuda"


[metrics]
# settings for sMPRT and eMPRT

n_random = 1 # number of randomized models
eMPRT = {n_bins = 10}
sMPRT = {n_samples = 7, sigma=0.2}
curve = {n_steps = 3, type = "interpolate"}
error = true


# -- Integrated Gradients
[method.IG]

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 10, trapezoid = false}

baseline_method = "black"


# # -- Guided Integrated Gradients (original version)
# [method.GIG]

# explanation_method = "guided_integrated_gradients"
# explanation_parameters = {n_steps = 50, p_optim = 0.1}

# baseline_method = "black"


# # -- Guided Integrated Gradients reimagined
# [method.GIG2]

# explanation_method = "guided_integrated_gradients2"
# explanation_parameters = {step_size = 30, p_optim = 0.1, trapezoid = false}

# baseline_method = "black"


# # -- Iterative Integrated Gradients
# [method.IIG]

# explanation_method = "integrated_gradients"
# explanation_parameters = {n_steps = 10, trapezoid = false}

# baseline_method = "noisy_target"
# baseline_parameters = {noise = 0.1}


# [method.IIG.iterate]

# n_iterations = 4
# noise = 0.1
# explanation_transforms = ["abs", "mean"]

# perturbation_method = "inpaint_by_quantile"
# perturbation_parameters = {quantile = 0.4, radius = 5}


# # -- SmoothGrad + Integrated Gradients
# [method.SmoothIG]

# explanation_method = "smooth_integrated_gradients"
# explanation_parameters = {n_steps = 50, trapezoid = false, noise = 0.2, n_samples = 30}

# baseline_method = "black"
