[general]

image_path = "./data/ImageNet/ILSVRC/Data/CLS-LOC/test/"
out_path = "output/resnet50"
n_samples = 1000
batch_size = 10
classificator = "resnet50"
apply_softmax = false
device = "cuda"


[perturbation_curve]
# settings for the perturbation curve

n_steps = 11
type = "interpolate"


[MPRT]
# settings for sMPRT and eMPRT

n_random = 1 # number of randomized models
eMPRT = {n_bins = 100}
sMPRT = {n_samples = 50, sigma=0.2}


# -- SmoothGrad + Integrated Gradients
[method.SmoothIG]

explanation_method = "smooth_integrated_gradients"
explanation_parameters = {n_steps = 50, trapezoid = false, noise = 0.2, n_samples = 30}

baseline_method = "black"
