[general]

image_path = "D:/ImageNet/ILSVRC/Data/CLS-LOC/test/"
out_path = "output/resnet50"
n_samples = 1000
batch_size = 10
classificator = "resnet50"
apply_softmax = false
device = "cuda"


[perturbation_curve]
# settings for the perturbation curve

n_steps = 11
type = "interpolate"


[MPRT]
# settings for sMPRT and eMPRT

n_random = 3 # number of randomized models
eMPRT = {n_bins = 100}
sMPRT = {n_samples = 50, sigma=0.2}


# -- Integrated Gradients
[method.IG]

description = "Integrated Gradients - Baseline method"

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 50, trapezoid = false}

baseline_method = "black"


# -- Integrated Gradients with noisy target as baseline
[method.IG-noisy]

description = "Integrated Gradients with noisy target as baseline"

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 50, trapezoid = false}

baseline_method = "noisy_target"
baseline_parameters = {noise = 0.1}


# -- Guided Integrated Gradients
[method.GIG]

description = "Guided Integrated Gradients - Original version"

explanation_method = "guided_integrated_gradients"
explanation_parameters = {n_steps = 20, p_optim = 0.1}

baseline_method = "black"


# # -- Guided Integrated Gradients reimagined
# [method.GIG2]

# description = "Integrated Gradients - Reimagined"

# explanation_method = "guided_integrated_gradients2"
# explanation_parameters = {step_size = 30, p_optim = 0.1, trapezoid = false}

# baseline_method = "black"


# -- Iterative Integrated Gradients
[method.IIG]

description = "Iterative Integrated Gradients"

explanation_method = "integrated_gradients"
explanation_parameters = {n_steps = 10, trapezoid = false}

baseline_method = "noisy_target"
baseline_parameters = {noise = 0.1}

[method.IIG.iterate]

n_iterations = 4
noise = 0.1
explanation_transforms = ["abs", "mean"]

perturbation_method = "inpaint_by_quantile"
perturbation_parameters = {quantile = 0.4, radius = 5}
